### ISSUE TITLE
Argument list too long for HMP

### ISSUE THREAD

**Issue by simonepignotti** [prophyle/prophyle#261] opened 2017-09-21 15:22 UTC
When building the index for HMP, the number of file to concatenate exceeds the shell's maximum number of arguments. A possible solution is to use the `fasta_offset` attribute of the nodes to create the full fasta files.
```
phyle/hmp/NZ_ABBZ01006731.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006732.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006733.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006734.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006735.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006736.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006737.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006738.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006739.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006740.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006741.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006742.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006743.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006744.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006745.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006746.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006747.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006748.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006749.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006750.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006751.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006752.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006753.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006754.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006755.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006756.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006757.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006758.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006759.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006760.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006761.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006762.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006763.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006764.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006765.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006766.fna /mnt/disk/pignotti/pro
phyle/hmp/NZ_ABBZ01006767.fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006768.
fna /mnt/disk/pignotti/prophyle/hmp/NZ_ABBZ01006769.fna | dustmasker -infmt fa
sta -outfmt fasta | sed '/^>/! s/[^AGCT]/N/g'  > ./422289.full.fa
make: execvp: /usr/bin/env: Argument list too long
make: *** [Makefile:44042: 422289.full.fa.complete] Error 127
make: Leaving directory '/mnt/disk/pignotti/prophyle/idx_hmp/propagation'
[prophyle] 2017-09-21 14:46:46 Unfinished, an error occurred (error code 2, 73
0.0 MB used): make -j 24 -C idx_hmp/propagation V=1
Error: K-mer propagation has not been finished because of an error. See messag
es above.
```

**Comment by karel-brinda** [comment] 2017-09-21 16:12
Could put here the entire log? Which node is it?

**Comment by karel-brinda** [comment] 2017-09-21 16:15
Btw. We should definitely change the strategy of dealing with HMP. Splitting the FASTA file by individual sequences causes many problems (too many files are created, etc.).

**Comment by simonepignotti** [comment] 2017-09-21 16:57
The problem is node 422289, it has many fasta associated because it is not a coplete genome. I looked into one at random:
```
>BACT_204|gi|153882178|ref|NZ_ABBZ01006737.1| Beggiatoa sp. PS contig14825, whole genome shotgun sequence
TGTTTTCAAAGCCCAGGACTGCACTCCACAGCATTAGAGGTCTGTGAGATGCTTATAGTG
ATACGCGAACCAACATGTTGTGTTCAATTAGCTTC
```
Should I filter sequences longer than a certain threshold? I can do it easily with the fasta indexes.
BTW this is happening only now because I managed to find almost all the taxids using eutils. The problem was that many of the sequences in the HMP reference were deleted from RefSeq. Honestly I start to be a bit suspicious about this selection...

[hmp.nw.txt](https://github.com/karel-brinda/prophyle/files/1322095/hmp.nw.txt)
[hmp_err.txt](https://github.com/karel-brinda/prophyle/files/1322097/hmp_err.txt)
[hmp_out.txt](https://github.com/karel-brinda/prophyle/files/1322096/hmp_out.txt)

**Comment by karel-brinda** [comment] 2017-09-25 21:26
This part of our code will need a major revision. The main issue here is that ProPhyle splits up the HMP reference file by sequences and not by strains. How difficult would be to fix this?

**Comment by simonepignotti** [comment] 2017-09-27 07:03
Sequences coming from the same sequencing experiment should have consecutive accession number (I haven't verified yet, but it looks like this is always verified). If so, not so difficult.

**Comment by karel-brinda** [comment] 2017-11-20 23:17
@simonepignotti I plan to fix this issue together with moving HMP to Zenodo.

**Comment by karel-brinda** [comment] 2018-05-07 21:46
Duplicate of #301.

**Closed by karel-brinda** 2018-05-07 21:46 UTC
Labels: bug
